// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQIkgce0BU3p0Jkq5ADQK0i2hxU_w3oVE',
    appId: '1:910236109160:web:f074c70ece2a2afc7f6edd',
    messagingSenderId: '910236109160',
    projectId: 'instok-15bdd',
    authDomain: 'instok-15bdd.firebaseapp.com',
    storageBucket: 'instok-15bdd.firebasestorage.app',
    measurementId: 'G-8BM0PQQ0P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNSlqnvL1RKrKbwf9XdJLqp64sC10lkjs',
    appId: '1:910236109160:android:672cc9e878ee740a7f6edd',
    messagingSenderId: '910236109160',
    projectId: 'instok-15bdd',
    storageBucket: 'instok-15bdd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-LLOmedK6OVuCzLK14wptqf-u523psos',
    appId: '1:910236109160:ios:75aaedef51efbeaa7f6edd',
    messagingSenderId: '910236109160',
    projectId: 'instok-15bdd',
    storageBucket: 'instok-15bdd.firebasestorage.app',
    iosBundleId: 'com.example.instok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQIkgce0BU3p0Jkq5ADQK0i2hxU_w3oVE',
    appId: '1:910236109160:web:4ec0d85f33c03c667f6edd',
    messagingSenderId: '910236109160',
    projectId: 'instok-15bdd',
    authDomain: 'instok-15bdd.firebaseapp.com',
    storageBucket: 'instok-15bdd.firebasestorage.app',
    measurementId: 'G-417KEXBQQB',
  );
}
